In [3]:
import emoji

In [4]:
## python support many built in functions like print
print("Hello world")

## you can multiply string it with the number of times you want to repeat
print("Hi " * 10)

## Python support emojis also ;-

print(emoji.emojize('Hi there! :thumbs_up:'))

# more print statement
## escape characters
print('Suraj\'s Tutorial:\t www.surajtutorial.com \nI\'am in new line')

## Ignore escape character --> r stands for raw text
print(r'Suraj\'s Tutorial:\t www.surajtutorial.com \nI\'am in new line')

## Operators 
# +
print(2 + 3)

# -
print(6 - 7)

# *
print(7*7)

# / ---> output will be in floating point representation
print(8/5)

# //  ----> floor division or integer division
print(8//5)

# %  ---> modulus (remainder)
print(8%5)

# ** --> power
print(2**3)

Hello world
Hi Hi Hi Hi Hi Hi Hi Hi Hi Hi 
Hi there! 👍
Suraj's Tutorial:	 www.surajtutorial.com 
I'am in new line
Suraj\'s Tutorial:\t www.surajtutorial.com \nI\'am in new line
5
-1
49
1.6
1
3
8


In [5]:
## Variables

print(2 + 3)
a = 2
b = 3

print(a+b)

a, b = 7, 8
print(a+b)

a + b

5
5
15


15

In [8]:
7 + 7

14

In [13]:
## use output from previous operation
# _ + 5

In [27]:
## String slicing

name = "Suraj"
print(name)
print(len(name))
print(name[0])
print(name[2])
print(name[len(name) - 1])
print(name[-1])
print(name[:])
print(name[0:2])
print(name[:2])
print(name[2:])
print(name[::-1])

Suraj
5
S
r
j
j
Suraj
Su
Su
raj
jaruS


In [28]:
## list in python

nums = [1,2,3,4,5]
print(nums[::-1])
names = ["Suraj", "Baloni"]
print(names[-1])
mix = [1,2,3,"Suraj","Baloni"]
print(mix[0], mix[-2])
lol = [nums, names]
print(lol)

## lists are mutable
nums.append(1)
# nums.clear()
another_nums = nums.copy()
print(another_nums)
print(nums.count(1))
nums.extend(names)
print(nums)

# print(nums.index('Suraj'))
# nums.insert(1,"Hey")
# print(nums)
# nums.pop(-4)
# print(nums)
# nums.remove("Suraj")
# print(nums)
# nums.reverse()
# print(nums)
# print(sorted([3,2,3,4,67], reverse=True))
# del nums[:1]
# nums.remove("Hey")
# print(nums)
# print(min(nums))
# print(max(nums))
# print(sum(nums))


[5, 4, 3, 2, 1]
Baloni
1 Suraj
[[1, 2, 3, 4, 5], ['Suraj', 'Baloni']]
[1, 2, 3, 4, 5, 1]
2
[1, 2, 3, 4, 5, 1, 'Suraj', 'Baloni']


In [142]:
## Tuples in python , unlike list tuples are immutable and represented by ()

myTuple = (1,2,3,4)
myTuple.index(2)
print(myTuple)



(1, 2, 3, 4)


In [18]:
445

445

In [20]:
print(_ + 1)

446


In [8]:
## sets in python

sets = {77,90,3,4,78,78}
print(sets)
lists = [5,3,2,1]
print(list(set(lists)))

{3, 4, 77, 78, 90}
[1, 2, 3, 5]


In [9]:
## More in variable

num = 1
print(id(num))
name = "Suraj"
print(id(name))

abc = 1
print(id(abc))
print(id(1))

## can be initialise constant in python : NO , but you can use captial letter to show the variable is a constat
PI = 3.14 ## PI = 3.15 can update the value of PI, but uppercase shows the intent that PI should be used as constant

## Check datatype of variable
print(type(PI))

4305308032
4523961176
4305308032
4305308032
<class 'float'>


In [171]:
## Data Types
# 1. None : If we assign nothing then its non type. in other language it is null
a = None
print(type(a))

# 2. Numeric : int, float, complex, bool
# 2.1. int:
num = 2
print(type(num))

# 2.2. float
num = 2.1
print(type(num))

#2.3 complex
num = 8 + 5j
print(type(num))

# 2.4 Boolean
status = False
print(type(status))


## TypeCast
print(int(5.3))
print(float(5))
print(complex(8,9))

a = range(0,10)



<class 'NoneType'>
<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
5
5.0
(8+9j)


In [193]:
## Dictionary: when we have key value pair
dictEx = {"name": "Suraj", "age":32, "education": {"id":"BCA","_id":"MCA"}}
print(dictEx.keys())
print(dictEx.values())
print(dictEx["education"]["_id"])

dict_keys(['name', 'age', 'education'])
dict_values(['Suraj', 32, {'id': 'BCA', '_id': 'MCA'}])
MCA


In [204]:
## Operators in python
# 1. Arithmetic Operators:  + , -, //, / ,*, **, %
print(10+11)

# 2. Assignment Operator: = , +=, *=, /=
a = 6
a,b = 6, 4
a = b

# 3. Unary operators = - , +
n = -6
print(-n)

# 3. Relational Operator:  >,<,==,!=, >=, <=
print(10 > 11)

# 4. Logical Operator: and, or, not
print(10 > 11 and 10 < 9)
print(not(10 > 11 or 10 > 9))



21
6
False
False
False


In [214]:
## Number system in python decimal, binary, oct, hex
a = 10
print(bin(a))
print(oct(a))
print(hex(a))
print(0xfff)

0b1010
0o12
0xa
4095


In [220]:
## Swap two numbers
a = 10
b = 12
temp = a
a = b
b = temp
print(a, b)

a,b = 6,12
b,a = a,b
print(a, b)

12 10
12 6


In [2]:
## Bitwise operators: Compliment ~ , And & , Or |, XOR ^, Left Shift << , Right shift >>

# print(~12)

# print(12 & 13)
# print(12 | 13)
# print(12 ^ 14)
# print(10 << 2)
# print(12 >> 2)

In [242]:
## import math
import math
print(math.sqrt(25))
print(math.floor(2.99))
print(math.ceil(2.99))
print(math.pow(2,3))
print(math.pi)
print(math.exp(10))

5.0
2
3
8.0
3.141592653589793
22026.465794806718


In [30]:
## input()
import sys

a = input("enter a number") ## it will take everything as string
print(type(a))
print(int(a) + 10)

expn = eval(input("enter an expn"))
print(expn)


enter a number10
<class 'str'>
20
enter an expn2+3
5


In [251]:
## if, elif, else statement

a = 10

if True:
    print("Iam true")
if a > 11:
    print("Iam greater then 11")
else:
    print("Iam less then 11")
    
if a > 10:
    print("Iam greater then 10")
elif a < 10:
    print("Iam less then 10")
else:
    print("Iam equal to 10")

Iam true
Iam less then 11
Iam equal to 10


In [258]:
## While loop
i = 0
while i<5:
    print("Iam less then 5")
    i = i + 1

Iam less then 5
Iam less then 5
Iam less then 5
Iam less then 5
Iam less then 5


In [265]:
# For loop

for i in range(10,0,-1):
    print(i, end="")

10987654321

In [269]:
# Break and Continue
for i in range(0,10):
    if i%2==0:
        continue
    elif i==9:
        break
    elif i>5:
        pass
    else:
        print(i)



1
3
5


In [276]:
# print patterns with one @ in one print statement
# @@@@
# @@@@
# @@@@
# @@@@

for j in range(0,4):
    for i in range(0,4):
        print("@", end="")
    print()

@@@@
@@@@
@@@@
@@@@


In [281]:
# print patterns with one @ in one print statement
# @
# @@
# @@@
# @@@@

for i in range(1,5):
    for j in range(0,i):
        print("@", end="")
    print()


@
@@
@@@
@@@@


In [289]:
# print patterns with one @ in one print statement
# @@@@
# @@@
# @@
# @

for i in range(4,0,-1):
    for j in range(0,i):
        print("@", end="")
    print()

@@@@
@@@
@@
@


In [293]:
## Print prime number from 1 to 100

for i in range(1,101):
    flag = 0
    for j in range(2,i):
        if i % j == 0:
            flag = 1
    if flag == 0:
        print(str(i)+ " is a prime number")
    else:
        print(str(i)+ " is not a prime number")

1 is a prime number
2 is a prime number
3 is a prime number
4 is not a prime number
5 is a prime number
6 is not a prime number
7 is a prime number
8 is not a prime number
9 is not a prime number
10 is not a prime number
11 is a prime number
12 is not a prime number
13 is a prime number
14 is not a prime number
15 is not a prime number
16 is not a prime number
17 is a prime number
18 is not a prime number
19 is a prime number
20 is not a prime number
21 is not a prime number
22 is not a prime number
23 is a prime number
24 is not a prime number
25 is not a prime number
26 is not a prime number
27 is not a prime number
28 is not a prime number
29 is a prime number
30 is not a prime number
31 is a prime number
32 is not a prime number
33 is not a prime number
34 is not a prime number
35 is not a prime number
36 is not a prime number
37 is a prime number
38 is not a prime number
39 is not a prime number
40 is not a prime number
41 is a prime number
42 is not a prime number
43 is a prime n

In [35]:
### Array in python
from array import *

arr = array("d", [10.4,2,3,5,7,8])
print(arr)
arr.reverse()
print(arr)
print(arr.buffer_info())
print(arr.typecode)
print(arr[0])
arr.append(12)
print(arr)
print(arr.count(1))
for nums in arr:
    print(nums)


array('d', [10.4, 2.0, 3.0, 5.0, 7.0, 8.0])
array('d', [8.0, 7.0, 5.0, 3.0, 2.0, 10.4])
(4524364640, 6)
d
8.0
array('d', [8.0, 7.0, 5.0, 3.0, 2.0, 10.4, 12.0])
0
8.0
7.0
5.0
3.0
2.0
10.4
12.0


In [20]:
# Take input from user to make an array

from array import *
arr = array("i",[])

size = int(input("Enter the length of an array"))

for i in range(size):
    arr.append(int(input("Enter the "+str(i)+" element")))
    

print(arr)
# print(arr.index(3))

Enter the length of an array3
Enter the 0 element1
Enter the 1 element2
Enter the 2 element1
array('i', [1, 2, 1])


In [41]:
## Ways of defining arrays using numpy
import numpy as np

# 1. array
arr = np.array([1,2,3,4,5,3], int)
print(arr)

# 2. linspace (start, end, size)

arr = np.linspace(2,15,3)  ## (a,b,c) (b-a)/(c-1) + a
print(arr)

# 3. arange (start, end, steps)

arr = np.arange(2,14,2)
print(arr)

# 4. logspace (start, end, size)

arr = np.logspace(1,40,5)
print(arr)

# # 5. zero (len)

arr = np.zeros(5)
print(arr)

# # 5. ones (len)

arr = np.ones(5)
print(arr)


[1 2 3 4 5 3]
[ 2.   8.5 15. ]
[ 2  4  6  8 10 12]
[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [408]:
## Operations on numpy array

arr = np.array([1,2,87,4,5])
print(arr + 5)
print(arr * 5)
print(arr / 5)
print(arr % 5)
print(np.sqrt(arr))
print(np.cos(arr))
print(np.sin(arr))
print(np.tan(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.average(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.msort(arr))
print(np.concatenate([arr, np.array([1,2,3,4])]))

[ 6  7 92  9 10]
[  5  10 435  20  25]
[ 0.2  0.4 17.4  0.8  1. ]
[1 2 2 4 0]
[1.         1.41421356 9.32737905 2.         2.23606798]
[ 0.54030231 -0.41614684  0.56975033 -0.65364362  0.28366219]
[ 0.84147098  0.90929743 -0.82181784 -0.7568025  -0.95892427]
[ 1.55740772 -2.18503986 -1.44241747  1.15782128 -3.38051501]
87
1
99
19.8
19.8
4.0
[ 1  2  4  5 87]
[ 1  2 87  4  5  1  2  3  4]


In [43]:
# Copy arr into another arr

## Shallow copy
arr1 = [1,2,3,4,5,6]
arr2 = arr1

print(arr1)
print(arr2)
arr2[0] = 5
print(arr1)
print(arr2)

## Deep copy
arr1 = [1,2,3,4,5,6]
arr2 = arr1.copy()

print(arr1)
print(arr2)
arr1[0] = 5
print(arr1)
print(arr2)



[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[5, 2, 3, 4, 5, 6]
[5, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[5, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [15]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1.view()
print(id(arr1))
print(id(arr2))

arr1[0] = 67
print(arr1)
print(arr2)


4524147776
4707658608
[67  2  3  4  5]
[67  2  3  4  5]


In [44]:
### N dimensional array

arr1 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,12]
])

print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

arr2 = arr1.flatten()
print(arr2)

### Matrices 

m = np.matrix(arr1)
print(m)

m = np.matrix('1,2,3;2,4,6;6,8,8')
print(m.T)
print(m.diagonal())
m1 = np.matrix('3,2,1;2,4,4;4,2,8')

print(m1 + m)
print(m1 * m)


2
10
int64
[ 1  2  3  4  5  6  7  8  9 12]
[[ 1  2  3  4  5]
 [ 6  7  8  9 12]]
[[1 2 6]
 [2 4 8]
 [3 6 8]]
[[1 4 8]]
[[ 4  4  4]
 [ 4  8 10]
 [10 10 16]]
[[13 22 29]
 [34 52 62]
 [56 80 88]]


In [65]:
## Functions

def greet():
    print("Hello Suraj")
    
def add_sub(a, b):
    return a+b, b-a
    
greet()
add, sub = add_sub(10,5)
print(add)
print(sub)

## when sending parameter: there is no concept of call by value or call by reference

## Types of arguments : actual and formal argument
## actual arg has four properties: position, keyword, default, variable length

def person(name, age):    ## formal args, default arg
    print(name)
    print(age*5)
    
person(age=23, name="Suraj")      ## actual args

# person(38, "Suraj")  ##position: as in function we are expecting name first and age second, position of arg can cause confusion and can lead to errors
# person( 38,"SUraj") ## Keyword: position does not matters, parameters are accessed through keyword
# person("Suraj",12) ## Default args


# plt(1,2,3,4)

def add(a, *b):   ## Variable length args
    print(a)
    print(b)
    
add(1,2,4,5,6,8,9)

def person(name, **aa):  ## keyword variable lenghth args
    print(name)
    print(aa)
    
person(name=28, place="Chennai", mob=788787878, aaa="Suraj")

    

Hello Suraj
15
-5
Suraj
115
1
(2, 4, 5, 6, 8, 9)
28
{'place': 'Chennai', 'mob': 788787878, 'aaa': 'Suraj'}


In [69]:
## Global and local variable

a = 10
b = 20

def something():
    global a;   ## telling function to access global varable
    print(globals()["a"]) ## accessing all global variables
    print(a)

something()
print(a, b)

10
10
10 20


In [494]:
### Fibbonacci series upto 100

frst = 0
sec = 1
third = 0
print(frst, sec, end=" ")
count = 0
while(third < 100):
    third = frst + sec
    frst = sec
    sec = third
    print(third, end=" ")

0 1 1 2 3 5 8 13 21 34 55 89 144 

In [3]:
## Factorial of a number

# num = 5
# fact = 1
# while(num>1):
#     fact = fact * num 
#     num = num -1
    
# print(fact)

# # Recursion

# def fact(n):
#     print(n)
#     if n ==0:
#         return 1
#     return n* fact(n-1)

# result = fact(5)
# print(result)

In [71]:
## Anonymous Functions in Python

from functools import *

f = lambda x : x*x

print(f(2))

# 1. Filter : When you have to filter specific element from a sequence

arr = [1,2,3,4,5,6,7,8,9]

evens = list(filter(lambda x: x%2==0, arr))
print(evens)

# 2. map : when you want to map a property to all the element of a sequence
add2 = list(map(lambda x: x+2, evens))
print(add2)

# 3. reduce: When you want to reduce a sequence to something e.g mean, sum

sums = reduce(lambda x,y:x+y, add2)
print(sums)

4
[2, 4, 6, 8]
[4, 6, 8, 10]
28


In [73]:
## Class


class Computer:
    
    def config(self):
        print("Yess")
        
    

        
obj = Computer()
obj.config()

class Student:
    
    def __init__(self,name,roll):
        self.name = name
        self.roll = roll
        
    
    def details(self):
        print(self.name, self.roll)
        
obj1 = Student("Suraj",5)
obj2 = Student("Baloni",78)

obj1.details()
obj2.details()



Yess
Suraj 5
Baloni 78


In [37]:
# print(__name__)

In [4]:
### Class Concept:
## Instance method (__init__, self), class method(cls, @classmethod), static method(@staticmethod)
##  Accessor Method(getter: where we just fetch the value), Mutator method (Setter: Where we update the value)

class Trainees:
    
    center = "Ignite1"
    
    def __init__(self,name,ignite):   ## Instance Method
        self.name = name
        self.ignite = ignite
        self.ignite = "SUraj"
#         global center
        
        
    def set_name(self,name):  ## Mutator method
        self.name = name
        return self.name
    
    def get_name(self):   ## Accessor Method
        return self.name
    
    @classmethod
    def updateCenter(cls, name):
        cls.center = name
        return cls.center
    
    @staticmethod
    def display_trainees2(a,b):
        print("Inside static method")
    
    
        
t1 = Trainees("Suraj",368)
# print(t1.name)
# print("Accessor Method(before): "+ t1.get_name())
# print("Mutator Method: "+ t1.set_name("TeamPriya"))
# print("Accessor Method(after): "+ t1.get_name())
print("Class variable center: "+ t1.center)
print("Class variable center: "+ t1.updateCenter("OpenIgniteXX"))
print("Class variable center: "+ Trainees.center)
t1.display_trainees2(1,22)
    
    
    
# A class method is a method which is bound to the class and not the object of the class.
# They have the access to the state of the class as it takes a class parameter that points to the
# class and not the object instance.
# It can modify a class state that would apply across all the instances of the class.
# For example it can modify a class variable that will be applicable to all the instances


# In general, static methods know nothing about class state. They are utility type methods that take 
# some parameters and work upon those parameters. On the other hand class methods must have class as parameter.
# We use @classmethod decorator in python to create a class method and we use @staticmethod decorator to 
# create a static method in python.


Class variable center: Ignite1
Class variable center: OpenIgniteXX
Class variable center: OpenIgniteXX
Inside static method


In [5]:
## Inheritance In python

class A:
    def feature1(self):
        print("Iam feature one")

    def feature2(self):
        print("Iam feature two")
        
class B(A):   ## Simple Inheritance
    def feature3(self):
        print("Iam feature three")

    def feature4(self):
        print("Iam feature four")


class C(B):   ## Multi level Inheritance
    def feature5(self):
        print("Iam feature five")

    def feature6(self):
        print("Iam feature six")
        
class D:
    def feature7(self):
        print("Iam feature seven")
        
class E(C,D):  ## Multiple Inheritance
    def feature8(self):
        print("Iam feature eight")


a = A()
b = E()

b.feature5()

    

Iam feature five


In [10]:
## Constructor in inheritance, Method resolution order

class A:
    
    def __init__(self):
        print("init of A")
    
    def feature1(self):
        print("Iam feature one")

    def feature2(self):
        print("Iam feature two")
        
class C:
    
    def __init__(self):
        print("init of C")
    
    def feature4(self):
        print("Iam feature four")

    def feature5(self):
        print("Iam feature five")
        
class B(C,A):   ## 
    
    def __init__(self):     ## Comment constructor
        super().__init__()  ## Accessing the function of super class ,Method resolution order
        print("init of B")
    
    def feature3(self):
        print("Iam feature three")

    def feature4(self):
        print("Iam feature four")
        
        
a = A()
b = B()





init of A
init of C
init of B


In [543]:
## Ploymorphism in Python
# Duck typing
# Operator overloading
# Method overloading
# Method  overridding


In [61]:
## Duck Typing

# Eg. If a bird walks, quacks, swims like a duck.That bird is a duck

# class Myfunc:
    
#     def result(self):
#         print("Its mine")
        
# class Yourfunc(Myfunc):
    
#     def result(self):
#         print("Its yours")
        
# class Judge:
    
#     def __init__(self, decision):
#         decision.result()
        
# dec = Yourfunc()

# jud = Judge(dec)
        




In [11]:
def calc(a,b):
    print(a+b)
#     return a+b

calc(1,2)
calc('hello','world')
calc([1],[2])

3
helloworld
[1, 2]


In [15]:
#### OPERATOR overloading

# class Sample2:
#     def __init__(self,m1,m2):
#         self.m1 = m1
#         self.m2 = m2
    
#     def __add__(self,other):  ### Operator overloading
#         m1 = self.m1 - other.m2
#         m2 = self.m1 - other.m2
#         s3 = Sample(m1, m2)
#         return s3
    

class Sample:
    
    def __init__(self,m1,m2):
        self.m1 = m1
        self.m2 = m2
    
    def __add__(self,other):  ### Operator overloading
        m1 = self.m1 - other.m1
        m2 = self.m2 - other.m2
        s3 = Sample(m1, m2)
        return s3
        
        
        
s1 = Sample(5,6)
s2 = Sample(3,4)

s3 = s1 + s2
print(s3.m1)



2


In [8]:
## Method overloading and Method overridding

# Method overloading: using same method name with different args list

#  but we can only use the second product method, as python does not supports method overloading.
# We may define many method of same name and different argument but we can only use the latest defined method. 

class Example:
    
    def add(self,a):
        print(a,b,c)
        print("One")
        if a!=None and b!=None and c!=None:
            return a+b+c
        elif c==None and b!=None:
            return a+b
        else:
            return a
        
    def add(self,a,b=None,c=None):
        print(a,b,c)
        print("tWO")
        if a!=None and b!=None and c!=None:
            return a+b+c
        elif c==None and b!=None:
            return a+b
        else:
            return a
            
    
    
e = Example()

e.add(5)
e.add(5,4)


5 None None
tWO
5 4 None
tWO


9

In [14]:
### Method overriding 

class Father:
    def phone(self):
        print("Nokia 1108")

class Me(Father):
    def phone(self):
        super().phone()
        print("Samsung S9")
        
m = Me()
m.phone()
        

Nokia 1108
Samsung S9


In [21]:
## Errors: Complie time, Logical, Run time

a = 5 
b = 0

try:
    print(a/b)
except Exception as e:
    print("Exception occured:")
    print(e)

Exception occured:
division by zero


In [22]:
### Multithreading

from threading import *

class Example1(Thread):
    def run(self):
        for i in range(10):
            print("hello")

class Example2(Thread):
    def run(self):
        for i in range(10):
            print("Hi")
        
ex1 = Example1()
ex2 = Example2()

ex1.start()
ex2.start()

ex1.join()
ex2.join()
print("Bye")

hello
hello
Hihello
hello
hello
hello
hello
hello
hello
hello

Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Bye


In [ ]:
### Linear search , Binary Search, Bubble sort, selection sort