## Reinforcement Learning -Qtable

In [19]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output


In [54]:
## initialise the environment
env = gym.make("FrozenLake-v0")

[2019-12-11 19:21:23,455] Making new env: FrozenLake-v0


In [55]:
## initialise all required variable

action_space_size = env.action_space.n ## Number of action we can take i.e. Left, right, Up, Down
state_space_size = env.observation_space.n  ## Number os different states i.e grid of size 4*4, 16 different states that an agent can change

## initialize q-table (4*4 grid) to all zeros
q_table = np.zeros((state_space_size , action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [56]:
num_episode = 1000 ## Number of different attempts agent can take
max_step_per_episode = 100 ## Number of step agent can take in one episode
learning_rate = 0.1
discount_rate = 0.99


## Explain_Exploration
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [62]:
## Learning of agent

rewards_all_episode = [] ## 
for episode in range(num_episode):
    state = env.reset()
    done = False
    reward_current_episode = 0
    
    for step in range(max_step_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action) ## Step taken to change state
        q_table[state,action] = q_table[state,action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
        
        state = new_state
        reward_current_episode += reward
        
        if done:
            break
    
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    rewards_all_episode.append(reward_current_episode)
    
print(q_table)
    

[[0.46513474 0.43103342 0.44277339 0.43544142]
 [0.27819846 0.17144955 0.18826956 0.40156416]
 [0.34820023 0.28691688 0.27719863 0.3054823 ]
 [0.13138783 0.20823706 0.13773312 0.27742716]
 [0.47656083 0.29481313 0.29257991 0.23184208]
 [0.         0.         0.         0.        ]
 [0.24612189 0.16467723 0.28733029 0.10572149]
 [0.         0.         0.         0.        ]
 [0.29465744 0.328133   0.31923999 0.50410656]
 [0.31727776 0.55585588 0.36505744 0.34257252]
 [0.49224693 0.34395975 0.33675278 0.22295893]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.21263412 0.31704263 0.63201141 0.45888577]
 [0.55960894 0.87863507 0.7083325  0.62756738]
 [0.         0.         0.         0.        ]]


In [63]:
for episode in range(3):
    state = env.reset()
    done = False
    print("Episode")
    
    time.sleep(1)
    
    for steps in range(max_step_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait = True)
            env.render()
            if reward == 1:
                print("Win")
            else:
                print("Lost")
            clear_output(wait=True)
            break
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
Win
